name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci
         ref: ci-wippersnapper

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: Install extra Arduino libraries
      run: |
        git clone --quiet https://github.com/adafruit/Adafruit_TinyUSB_Arduino /home/runner/Arduino/libraries/Adafruit_TinyUSB_Arduino

    - name: test platforms
      run: |
        echo "running from $(pwd)"
        echo "arduino-cli available at: $(which arduino-cli)"
        python3 ci/build_platform.py rp2040_platforms
        for platform in pico_rp2040_tinyusb pico_rp2040_tinyusb_host pico_rp2350 pico_rp2350_tinyusb pico_rp2350_tinyusb_host picow_rp2040 picow_rp2040_tinyusb main_platforms; do
          python3 ci/build_platform.py $platform --skip-uninstall
        done

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit SleepyDog Library"
      run: bash ci/doxy_gen_and_deploy.sh
